name: phone_auth_handler_demo
description: Demo for the package firebase_phone_auth_handler on pub.dev

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  pinput: ^5.0.0
  firebase_core: ^3.6.0
  easy_container: ^1.0.5
  intl_phone_field: ^3.2.0
  firebase_phone_auth_handler:
    path: "../"

dev_dependencies:
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true